operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    admin-ui-sdk:
      license: Apache-2.0
      actions:
        registration:
          function: actions/registration/index.js
          web: 'yes'
          runtime: 'nodejs:20'
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: false
            final: true
    feed-generator:
      license: Apache-2.0
      inputs:
        LOG_LEVEL: debug
        apiKey: $SERVICE_API_KEY
        AC_GRAPHQL_URL: $AC_GRAPHQL_URL
        store: $AC_DEFAULT_STORE_CODE
        OAUTH_ORG_ID: $OAUTH_ORG_ID
        OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
        OAUTH_CLIENT_SECRET: $OAUTH_CLIENT_SECRET
        OAUTH_TECHNICAL_ACCOUNT_ID: $OAUTH_TECHNICAL_ACCOUNT_ID
        OAUTH_TECHNICAL_ACCOUNT_EMAIL: $OAUTH_TECHNICAL_ACCOUNT_EMAIL
        OAUTH_SCOPES: $OAUTH_SCOPES
        COMMERCE_BASE_URL: $COMMERCE_BASE_URL
        COMMERCE_CONSUMER_KEY: $COMMERCE_CONSUMER_KEY
        COMMERCE_CONSUMER_SECRET: $COMMERCE_CONSUMER_SECRET
        COMMERCE_ACCESS_TOKEN: $COMMERCE_ACCESS_TOKEN
        COMMERCE_ACCESS_TOKEN_SECRET: $COMMERCE_ACCESS_TOKEN_SECRET
        COMMERCE_HUBSPOT_CONTACT_ID_FIELD: $COMMERCE_HUBSPOT_CONTACT_ID_FIELD
        AC_ENVIRONMENT_ID: $AC_ENVIRONMENT_ID
      actions:
        getConfig:
          function: actions/getConfig/index.js
          web: 'yes'
          runtime: nodejs:20
          annotations:
            require-adobe-auth: true
            final: true
        saveFeed:
          function: actions/saveFeed/index.js
          web: 'yes'
          runtime: nodejs:20
          annotations:
            require-adobe-auth: true
            final: true
        deleteFeed:
          function: actions/deleteFeed/index.js
          web: 'yes'
          runtime: nodejs:20
          annotations:
            require-adobe-auth: true
            final: true
        getAllFeeds:
          function: actions/getAllFeeds/index.js
          web: 'yes'
          runtime: nodejs:20
          annotations:
            require-adobe-auth: true
            final: true
        getFeedByUuid:
          function: actions/getAllFeeds/getByUuid.js
          web: 'yes'
          runtime: nodejs:20
          annotations:
            require-adobe-auth: true
            final: true
        regenerateFeed:
          function: actions/regenerateFeed/index.js
          web: 'yes'
          runtime: nodejs:20
          inputs:
            providerId: $FEED_GENERATOR_PROVIDER_ID
            eventCode: feed.generate
          annotations:
            require-adobe-auth: true
            final: true
        processGeneration:
          function: actions/regenerateFeed/generate.js
          web: 'no'
          runtime: nodejs:20
          inputs:
            eventCode: feed.generate
          annotations:
            require-adobe-auth: true
            final: true
          relations:
            event-listener-for:
              - feed.generate
        generateByCron:
          function: actions/regenerateFeed/generateByCron.js
          web: 'no'
          runtime: nodejs:20
          annotations:
            require-adobe-auth: true
            final: true
        getAllStores:
          function: actions/magentoActions/getAllStores.js
          web: 'yes'
          runtime: nodejs:20
          annotations:
            require-adobe-auth: true
            final: true
        getGqlSchema:
          function: actions/magentoActions/getGqlSchema.js
          web: 'yes'
          runtime: nodejs:20
          annotations:
            require-adobe-auth: true
            final: true
      triggers:
        everyHalfOfHour:
          feed: /whisk.system/alarms/interval
          inputs:
            minutes: 30
      rules:
        everyHalfOfHourRule:
          trigger: everyHalfOfHour
          action: generateByCron